// server.js - Universal production entrypoint for Hostmattic on Coolify (Nixpacks & Docker)
const path = require('path');
const fs = require('fs');

// Ensure hostname binds to all interfaces inside Docker / Coolify container
process.env.HOSTNAME = process.env.HOSTNAME || '0.0.0.0';
process.env.PORT = process.env.PORT || '3000';

const standaloneServer = path.join(__dirname, '.next', 'standalone', 'server.js');

if (fs.existsSync(standaloneServer)) {
  // Standalone mode generated by Next.js
  console.log(`[Hostmattic] Starting Next.js standalone server on ${process.env.HOSTNAME}:${process.env.PORT}...`);
  require(standaloneServer);
} else {
  // Fallback standard Next.js production server
  console.log(`[Hostmattic] Starting Next.js standard server on ${process.env.HOSTNAME}:${process.env.PORT}...`);
  const next = require('next');
  const http = require('http');
  const port = parseInt(process.env.PORT, 10);
  const hostname = process.env.HOSTNAME;

  const app = next({ dev: false, dir: __dirname });
  const handle = app.getRequestHandler();

  app.prepare().then(() => {
    http.createServer((req, res) => {
      handle(req, res);
    }).listen(port, hostname, () => {
      console.log(`[Hostmattic] Ready on http://${hostname}:${port}`);
    });
  }).catch((err) => {
    console.error('[Hostmattic] Failed to start server:', err);
    process.exit(1);
  });
}
